INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Luan', 'Computação');
INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Otário', 'Computação');
INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Alemão', 'Gastronomia');